name: ci

"on":
  push:
    paths:
      - ".github/workflows/ci.yml"
      - "lib/**"
      - "*.gemspec"
      - "spec/**"
      - "Rakefile"
      - "Gemfile"
      - ".rubocop.yml"
  pull_request:
    branches:
      - master
  create:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "2.6"
          - "2.5"
          - "2.4"
          - "2.3"
          - "jruby"
        db:
          - sqlite3
          - mysql
          - postgresql
    steps:
      - uses: actions/checkout@v1
      - name: Install package dependencies
        run: "[ -e $APT_DEPS ] || sudo apt-get install -y --no-install-recommends $APT_DEPS"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
      - name: Install latest bundler
        run: |
          gem install bundler --no-document
      - name: Bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Run all tests
        run: script/ci
      env:
        DB: ${{matrix.db}}
    services:
      mysql:
        image: mysql:5.7
        ports:
        - 3307:3306
        env:
          HANAMI_DATABASE_USERNAME: hanami
          HANAMI_DATABASE_PASSWORD: hanami
          HANAMI_DATABASE_NAME: hanami_model
      postgres:
        image: postgres:13
        ports:
        - 5433:5432
        env:
          HANAMI_DATABASE_USERNAME: hanami
          HANAMI_DATABASE_PASSWORD: hanami
          HANAMI_DATABASE_NAME: hanami_model
